export const SERVICE = {
  Accreditation: Symbol.for('AccreditationService'),
  Attachment: Symbol.for('AttachmentService'),
  App: Symbol.for('AppService'),
  Notification: Symbol.for('NotificationService'),
  Credits: Symbol.for('CreditsService'),
  Registries: Symbol.for('RegistriesService'),
  Reports: Symbol.for('ReportsService'),
  CreditForAccreditive: Symbol.for('CFA_DealService'),
  Messages: Symbol.for('MessagesService'),
  Banks: Symbol.for('BanksService'),
  User: Symbol.for('UserService'),
  Bic: Symbol.for('BicService'),
  Support: Symbol.for('SupportService'),
  Dictionary: Symbol.for('DictionaryService'),
  Discussion: Symbol.for('DiscussionService'),
  CFA_Reports: Symbol.for('CFA_ReportsService'),
  CFA_Draft: Symbol.for('CFA_DraftService'),
  WidgetDeals: Symbol.for('WidgetDealsService'),
  WidgetCountries: Symbol.for('WidgetCountriesService'),
  WidgetCredit: Symbol.for('WidgetCreditService'),
  WidgetIndustry: Symbol.for('WidgetIndustryService'),
  WidgetExport: Symbol.for('WidgetExportService'),
};
