// @todo: со временем избавиться от этих статусов

/**
 * CREDIT_CREATED - 'Поданная заявка'
 * CREDIT_DOCS_OK - 'Документы размещены'
 * CREDIT_ENTER_KO - 'Выход на КО'
 * CREDIT_APPROVED - 'Согласованно'
 * CREDIT_REJECTED - 'Не согласованно'
 * REGISTERS_NEW - 'Новый'
 * REGISTERS_APPROVED - 'Принят'
 * REGISTERS_REJECTED - 'Отклонен'
 * REQUEST_CREATED - 'Создан'
 * REQUEST_IN_PROGRESS - 'В процессе'
 * REQUEST_ADDITIONAL_INFO_REQUIRED - 'Требуется дополнительная информация'
 * REQUEST_DISCUSSION - 'Рассмотрение'
 * REQUEST_ACCEPTED - 'Одобрен'
 * REQUEST_REJECTED - 'Отклонен'
 * REPORTS_CREATED - 'Новый'
 * REPORTS_APPROVED - 'Принят'
 * ACCREDITATION_CREATED - 'Создана'
 * ACCREDITATION_DISCUSSION - 'На рассмотрении'
 * ACCREDITATION_REJECTED - 'Отклонена'
 */

export enum EStatus {
  CREDIT_CREATED = 'CREDIT_CREATED',
  CREDIT_DOCS_OK = 'CREDIT_DOCS_OK',
  CREDIT_ENTER_KO = 'CREDIT_ENTER_KO',
  CREDIT_APPROVED = 'CREDIT_APPROVED',
  CREDIT_REJECTED = 'CREDIT_REJECTED',
  REGISTERS_NEW = 'REGISTERS_NEW',
  REGISTERS_APPROVED = 'REGISTERS_APPROVED',
  REGISTERS_REJECTED = 'REGISTERS_REJECTED',
  REQUEST_CREATED = 'REQUEST_CREATED',
  REQUEST_IN_PROGRESS = 'REQUEST_IN_PROGRESS',
  REQUEST_ADDITIONAL_INFO_REQUIRED = 'REQUEST_ADDITIONAL_INFO_REQUIRED',
  REQUEST_DISCUSSION = 'REQUEST_DISCUSSION',
  REQUEST_ACCEPTED = 'REQUEST_ACCEPTED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  REPORTS_CREATED = 'REPORTS_CREATED',
  REPORTS_APPROVED = 'REPORTS_APPROVED',
  ACCREDITATION_CREATED = 'ACCREDITATION_CREATED',
  ACCREDITATION_DISCUSSION = 'ACCREDITATION_DISCUSSION',
  ACCREDITATION_REJECTED = 'ACCREDITATION_REJECTED',
}

export enum EStatusCodes {
  CREATED = 'CREATED',
  ON_CONSIDERATION = 'ON_CONSIDERATION',
  IN_PROGRESS = 'IN_PROGRESS',
  ADDITIONAL_INFO_REQUIRED = 'ADDITIONAL_INFO_REQUIRED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}
