export const API_CLIENT = {
  App: Symbol.for('AppApiClient'),
  Accreditation: Symbol.for('AccreditationApiClient'),
  Attachment: Symbol.for('AttachmentApiClient'),
  Registries: Symbol.for('RegistriesAPIClient'),
  Credits: Symbol.for('CreditsAPIClient'),
  Reports: Symbol.for('ReportsAPIClient'),
  CreditForAccreditive: Symbol.for('CFA_DealAPIClient'),
  Messages: Symbol.for('MessagesAPIClient'),
  Banks: Symbol.for('BanksAPIClient'),
  User: Symbol.for('UserAPIClient'),
  Bic: Symbol.for('BicApiClient'),
  Support: Symbol.for('SupportApiClient'),
  Dictionary: Symbol.for('DictionaryApiClient'),
  Discussion: Symbol.for('DiscussionAPIClient'),
  CFA_Reports: Symbol.for('CFA_ReportsAPIClient'),
  CFA_Draft: Symbol.for('CFA_DraftAPIClient'),
  WidgetDeals: Symbol.for('WidgetDealsAPIClient'),
  WidgetCountries: Symbol.for('WidgetCountriesApiClient'),
  WidgetCredit: Symbol.for('WidgetCreditApiClient'),
  WidgetIndustry: Symbol.for('WidgetIndustryAPIClient'),
  WidgetExport: Symbol.for('WidgetExportApiClient'),
};
